### ISSUE TITLE
Three Shuffles 

### ISSUE THREAD

**Issue by adammcd9** [liquidlight/slack-tea#1]
The only way I could get the script to work is if I removed two of the three shuffles on line 54 in tea.php. Not sure if this could be something to do with php version (I'm running 5.4).

**Comment by mikestreety** [comment]
Hmm, very odd - wouldn't see why a PHP couldn't shuffle a couple of times?

I'm running `PHP 5.2.17`

**Comment by mikestreety** [comment]
I've just set up a basic example at PHP Fiddle and got a warning - will make it only shuffle once and update the code. 

Will also look into using `mt_rand()` function

Thanks for the heads up!

**Comment by adammcd9** [comment]
No problem, I thought it was a bit weird that PHP didn't like doing it as well!
